services: 
  flask-app:
    image: nevish/ollamalangchainlg:0.7
    ports: 
      - 8501:8501
    networks:
      - my-network
    extra_hosts:
      - "host.docker.internal:host-gateway" 
    environment:
      - PYTHONUNBUFFERED=1

networks:
  my-network:
    driver: bridge